spring.application.name=21-SB-JunitTest
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/sbms26
spring.jpa.hibernate.dll-auto=update
spring.jpa.show-sql=true
