spring.application.name=20-KafkaProjectConsumer
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ramanrdx14@gmail.com
spring.mail.password=awstpbwiyktwyajo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true