spring.application.name=17-SB-JWTAuth
spring.datasource.url=jdbc:mysql://localhost:3306/sbms26_security
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

