spring.application.name=09-SB-RedisCache
spring.data.redis.username=default
spring.data.redis.password=udvOe9JOTk4512zeplqg12J759ONan78
spring.data.redis.url=person-rehydrated-stem-28442.db.redis.io
spring.data.redis.port=13038
