# DB1 - MySQL
spring.db1.datasource.jdbc-url=jdbc:mysql://localhost:3306/sbms26
spring.db1.datasource.username=root
spring.db1.datasource.password=root
spring.db1.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# DB2 - H2
spring.db2.datasource.jdbc-url=jdbc:h2:mem:testdb
spring.db2.datasource.username=sa
spring.db2.datasource.password=sa
spring.db2.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true